"""
PDF Report Generation Service using ReportLab.
Generates professional hospital-style A4 PDF reports.
"""
import base64
import io
import logging
import os
import tempfile
from datetime import datetime
from typing import Optional

import qrcode
from PIL import Image
from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import cm, mm
from reportlab.platypus import (
    HRFlowable,
    Image as RLImage,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

logger = logging.getLogger(__name__)

# Brand colors
PRIMARY_CYAN = colors.HexColor("#0891B2")
DARK_CYAN = colors.HexColor("#0E7490")
LIGHT_CYAN = colors.HexColor("#E0F7FA")
DARK_SLATE = colors.HexColor("#1E293B")
MEDIUM_SLATE = colors.HexColor("#475569")
LIGHT_SLATE = colors.HexColor("#94A3B8")
WHITE = colors.white
RED = colors.HexColor("#EF4444")
GREEN = colors.HexColor("#10B981")
AMBER = colors.HexColor("#F59E0B")


def _build_styles() -> dict:
    """Build custom paragraph styles."""
    styles = getSampleStyleSheet()
    custom = {
        "title": ParagraphStyle(
            "title",
            fontSize=22,
            textColor=PRIMARY_CYAN,
            fontName="Helvetica-Bold",
            spaceAfter=4,
            alignment=TA_CENTER,
        ),
        "subtitle": ParagraphStyle(
            "subtitle",
            fontSize=11,
            textColor=MEDIUM_SLATE,
            fontName="Helvetica",
            spaceAfter=2,
            alignment=TA_CENTER,
        ),
        "section_header": ParagraphStyle(
            "section_header",
            fontSize=12,
            textColor=WHITE,
            fontName="Helvetica-Bold",
            spaceAfter=6,
            spaceBefore=4,
        ),
        "body": ParagraphStyle(
            "body",
            fontSize=10,
            textColor=DARK_SLATE,
            fontName="Helvetica",
            spaceAfter=4,
            leading=14,
        ),
        "label": ParagraphStyle(
            "label",
            fontSize=9,
            textColor=MEDIUM_SLATE,
            fontName="Helvetica-Bold",
        ),
        "value": ParagraphStyle(
            "value",
            fontSize=10,
            textColor=DARK_SLATE,
            fontName="Helvetica",
        ),
        "disclaimer": ParagraphStyle(
            "disclaimer",
            fontSize=8,
            textColor=LIGHT_SLATE,
            fontName="Helvetica-Oblique",
            alignment=TA_CENTER,
            leading=11,
        ),
        "disease_name": ParagraphStyle(
            "disease_name",
            fontSize=16,
            textColor=PRIMARY_CYAN,
            fontName="Helvetica-Bold",
            spaceAfter=4,
        ),
    }
    return custom


async def generate_prediction_pdf(
    report_data: dict,
    gradcam_overlay_b64: Optional[str] = None,
) -> bytes:
    """
    Generate a professional A4 hospital-style PDF report.

    Args:
        report_data: Dict containing patient info, prediction results, doctor notes.
        gradcam_overlay_b64: Base64-encoded Grad-CAM overlay PNG.

    Returns:
        PDF as bytes.
    """
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        rightMargin=2 * cm,
        leftMargin=2 * cm,
        topMargin=2 * cm,
        bottomMargin=2 * cm,
    )

    styles = _build_styles()
    story = []

    # ─── Header ──────────────────────────────────────────────────────────────
    header_data = [
        [
            Paragraph("🦷 DENTAL AI", styles["title"]),
            "",
            Paragraph(
                f"Report ID: <b>{report_data.get('report_id', 'N/A')}</b><br/>"
                f"Date: {datetime.now().strftime('%d %B %Y, %H:%M')}<br/>"
                f"Generated by: AI Dental System",
                ParagraphStyle("right", fontSize=9, textColor=MEDIUM_SLATE,
                               fontName="Helvetica", alignment=TA_RIGHT),
            ),
        ]
    ]
    header_table = Table(header_data, colWidths=[8 * cm, 1 * cm, 8 * cm])
    header_table.setStyle(TableStyle([
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
    ]))
    story.append(header_table)
    story.append(HRFlowable(width="100%", thickness=2, color=PRIMARY_CYAN, spaceAfter=10))
    story.append(Paragraph("AI-Based Dental Disease Detection Report", styles["subtitle"]))
    story.append(Spacer(1, 8 * mm))

    # ─── Patient Information ──────────────────────────────────────────────────
    _section_header(story, "PATIENT INFORMATION", styles)
    patient = report_data.get("patient", {})
    patient_table_data = [
        [
            Paragraph("Patient Name", styles["label"]),
            Paragraph(patient.get("name", "—"), styles["value"]),
            Paragraph("Patient ID", styles["label"]),
            Paragraph(patient.get("id", "—"), styles["value"]),
        ],
        [
            Paragraph("Age", styles["label"]),
            Paragraph(str(patient.get("age", "—")), styles["value"]),
            Paragraph("Gender", styles["label"]),
            Paragraph(patient.get("gender", "—"), styles["value"]),
        ],
        [
            Paragraph("Email", styles["label"]),
            Paragraph(patient.get("email", "—"), styles["value"]),
            Paragraph("Phone", styles["label"]),
            Paragraph(patient.get("phone", "—"), styles["value"]),
        ],
    ]
    pt = Table(patient_table_data, colWidths=[3 * cm, 6 * cm, 3 * cm, 6 * cm])
    pt.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), LIGHT_CYAN),
        ("ROWBACKGROUNDS", (0, 0), (-1, -1), [WHITE, LIGHT_CYAN]),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#CBD5E1")),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ("LEFTPADDING", (0, 0), (-1, -1), 8),
    ]))
    story.append(pt)
    story.append(Spacer(1, 6 * mm))

    # ─── Prediction Result ────────────────────────────────────────────────────
    _section_header(story, "AI PREDICTION RESULT", styles)
    prediction = report_data.get("prediction", {})
    disease = prediction.get("predicted_class", "Unknown")
    confidence = prediction.get("confidence", 0)

    # Disease name + confidence
    result_data = [
        [
            Paragraph(f"Predicted Disease:", styles["label"]),
            Paragraph(f"<b>{disease}</b>", styles["disease_name"]),
            Paragraph("Confidence Score:", styles["label"]),
            Paragraph(f"<b>{confidence:.1f}%</b>",
                      ParagraphStyle("conf", fontSize=14, textColor=PRIMARY_CYAN,
                                     fontName="Helvetica-Bold")),
        ],
    ]
    rt = Table(result_data, colWidths=[3.5 * cm, 6 * cm, 3.5 * cm, 4 * cm])
    rt.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#F0F9FF")),
        ("TOPPADDING", (0, 0), (-1, -1), 10),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 10),
        ("LEFTPADDING", (0, 0), (-1, -1), 10),
        ("BOX", (0, 0), (-1, -1), 1.5, PRIMARY_CYAN),
    ]))
    story.append(rt)
    story.append(Spacer(1, 4 * mm))

    # Top-3 predictions table
    story.append(Paragraph("Top 3 Predictions:", styles["label"]))
    story.append(Spacer(1, 2 * mm))
    top3 = prediction.get("top3", [])
    top3_data = [["Rank", "Disease", "Confidence"]]
    for i, pred in enumerate(top3, 1):
        top3_data.append([str(i), pred.get("class", "—"), f"{pred.get('confidence', 0):.1f}%"])
    t3 = Table(top3_data, colWidths=[2 * cm, 10 * cm, 5 * cm])
    t3.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), PRIMARY_CYAN),
        ("TEXTCOLOR", (0, 0), (-1, 0), WHITE),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, 0), 10),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [WHITE, LIGHT_CYAN]),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#CBD5E1")),
        ("ALIGN", (0, 0), (-1, -1), "CENTER"),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
    ]))
    story.append(t3)
    story.append(Spacer(1, 6 * mm))

    # ─── Grad-CAM Images ──────────────────────────────────────────────────────
    if gradcam_overlay_b64:
        _section_header(story, "AI ATTENTION MAP (Grad-CAM)", styles)
        story.append(
            Paragraph(
                "The highlighted regions show the areas the AI model focused on when making its prediction. "
                "Brighter areas indicate higher importance in the diagnosis.",
                styles["body"],
            )
        )
        story.append(Spacer(1, 3 * mm))
        try:
            img_bytes = base64.b64decode(gradcam_overlay_b64)
            img_buffer = io.BytesIO(img_bytes)
            rl_img = RLImage(img_buffer, width=7 * cm, height=7 * cm)
            img_table = Table([[rl_img]], colWidths=[17 * cm])
            img_table.setStyle(TableStyle([("ALIGN", (0, 0), (-1, -1), "CENTER")]))
            story.append(img_table)
        except Exception as e:
            logger.warning(f"Could not embed Grad-CAM image: {e}")
        story.append(Spacer(1, 6 * mm))

    # ─── Disease Information ──────────────────────────────────────────────────
    disease_info = report_data.get("disease_info", {})
    if disease_info:
        _section_header(story, f"DISEASE INFORMATION: {disease.upper()}", styles)

        if disease_info.get("description"):
            story.append(Paragraph("<b>Description:</b>", styles["label"]))
            story.append(Paragraph(disease_info["description"], styles["body"]))
            story.append(Spacer(1, 3 * mm))

        if disease_info.get("symptoms"):
            story.append(Paragraph("<b>Symptoms:</b>", styles["label"]))
            for s in disease_info["symptoms"]:
                story.append(Paragraph(f"  • {s}", styles["body"]))
            story.append(Spacer(1, 3 * mm))

        if disease_info.get("treatment"):
            story.append(Paragraph("<b>Recommended Treatment:</b>", styles["label"]))
            for t in disease_info["treatment"]:
                story.append(Paragraph(f"  • {t}", styles["body"]))
            story.append(Spacer(1, 3 * mm))

        if disease_info.get("prevention"):
            story.append(Paragraph("<b>Prevention Tips:</b>", styles["label"]))
            for p in disease_info["prevention"]:
                story.append(Paragraph(f"  • {p}", styles["body"]))
            story.append(Spacer(1, 6 * mm))

    # ─── Doctor Review ────────────────────────────────────────────────────────
    doctor_review = report_data.get("doctor_review", {})
    _section_header(story, "DOCTOR REVIEW", styles)
    review_status = doctor_review.get("status", "Pending Review")
    doctor_name = doctor_review.get("doctor_name", "Not yet reviewed")

    review_data = [
        [Paragraph("Reviewed by:", styles["label"]),
         Paragraph(doctor_name, styles["value"])],
        [Paragraph("Review Status:", styles["label"]),
         Paragraph(review_status, styles["value"])],
        [Paragraph("Doctor Notes:", styles["label"]),
         Paragraph(doctor_review.get("notes", "—"), styles["value"])],
        [Paragraph("Prescription:", styles["label"]),
         Paragraph(doctor_review.get("prescription", "—"), styles["value"])],
    ]
    dr_table = Table(review_data, colWidths=[4 * cm, 13 * cm])
    dr_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (0, -1), LIGHT_CYAN),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#CBD5E1")),
        ("TOPPADDING", (0, 0), (-1, -1), 8),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
        ("LEFTPADDING", (0, 0), (-1, -1), 10),
    ]))
    story.append(dr_table)
    story.append(Spacer(1, 4 * mm))

    # Doctor signature line
    story.append(Spacer(1, 10 * mm))
    sig_data = [
        ["Doctor Signature: _____________________", "Date: _______________"]
    ]
    sig_table = Table(sig_data, colWidths=[12 * cm, 5 * cm])
    sig_table.setStyle(TableStyle([
        ("FONTNAME", (0, 0), (-1, -1), "Helvetica"),
        ("FONTSIZE", (0, 0), (-1, -1), 10),
        ("TEXTCOLOR", (0, 0), (-1, -1), MEDIUM_SLATE),
    ]))
    story.append(sig_table)
    story.append(Spacer(1, 10 * mm))

    # ─── Disclaimer + Footer ──────────────────────────────────────────────────
    story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#CBD5E1")))
    story.append(Spacer(1, 4 * mm))
    story.append(
        Paragraph(
            "⚠️ AI DISCLAIMER: This report is generated by an artificial intelligence system for "
            "informational purposes only and does not constitute a medical diagnosis. Always consult "
            "a qualified dental professional for proper diagnosis and treatment. The AI predictions "
            "may not be 100% accurate and should be reviewed by a licensed practitioner.",
            styles["disclaimer"],
        )
    )
    story.append(Spacer(1, 4 * mm))
    story.append(
        Paragraph(
            "© 2025 Dental AI — AI-Based Dental Disease Detection System | "
            "Powered by EfficientNet-B0 Deep Learning Model",
            styles["disclaimer"],
        )
    )

    doc.build(story)
    return buffer.getvalue()


def _section_header(story: list, title: str, styles: dict) -> None:
    """Add a styled section header bar."""
    header_data = [[Paragraph(f"  {title}", styles["section_header"])]]
    t = Table(header_data, colWidths=[17 * cm])
    t.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), PRIMARY_CYAN),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ("LEFTPADDING", (0, 0), (-1, -1), 8),
    ]))
    story.append(t)
    story.append(Spacer(1, 4 * mm))
